name: Line of code

on:
   workflow_dispatch:
  
    
#Define the jobs    
jobs:
   shell_scripting:
     runs-on: ubuntu-latest 
     
       
     # - name: Fetch Secrets
     #   env:
     #     PASSWORD: ${{ secrets.PASSWORD }}
     #   run: |
     #     echo "PASSWORD=$PASSWORD" >> $GITHUB_ENV
     #     echo "my secret is $PAT_TOKEN "
     steps:
     - name: run shell script
       run: |
          
          /usr/bin/git config --global --add safe.directory $GITHUB_WORKSPACE
          ORG_NAME="https://github.com/sivaboorla"
          GITHUB_TOKEN: ${{ secrets.API_TOKEN }}
          OUTPUT_FILE="repos.txt"
          PAGE=1
          PER_PAGE=100
          # Clear file before writing (optional)
          > "$OUTPUT_FILE"
          while true; do
             RESPONSE=$(curl -s -H "Authorization: token $GITHUB_TOKEN" \
             "https://api.github.com/orgs/$ORG_NAME/repos?per_page=$PER_PAGE&page=$PAGE")
             # Check if response is empty or an empty JSON array
             if [[ "$RESPONSE" == "[]" || -z "$RESPONSE" ]]; then
                break  # Stop if no more repositories
             fi
             # Extract repository names
             echo "$RESPONSE" | jq -r '.[].full_name' >> "$OUTPUT_FILE"
             ((PAGE++))
          done
          echo "Repositories saved to $OUTPUT_FILE"
           
        
          


  
