#java ci pipeline 
#name is an optional, it defines the name of pipeline.
name: learn-github-actions and CI PIPELINE FOR JAVA,MAVEN,DOCKERHUB.

#on is a keyword. it defines an event. 
on:
  push:
    branches:  [master]
 # pull_request:
#    branches: [ master ]



    
#Define the jobs    
jobs:
  build:
    runs-on: ubuntu-latest 
    steps:
    - uses: actions/checkout@v4
    - name: Java jdk setup
      uses: actions/setup-java@v1
      with:
        java-version: 12

    - name: maven Test
      run: mvn Test
   # - name: maven Integration test
  #    run: mvn IntegrationTest
    - name: maven build
      run: mvn Build
    

    



  
