name: shell

on:
  push:
    branches:  [ master ]
  pull_request:
    branches: [ master ]
  #workflow_diapatch:
  



    
#Define the jobs    
jobs:
   shell_scripting:
     runs-on: ubuntu-latest 
     
     steps:
     - name: Checkout code
       uses: actions/checkout@v2 
       
     - name: Fetch Secrets
       env:
         PASSWORD: ${{ secrets.PASSWORD }}
       run: |
         echo "PASSWORD=$PASSWORD" >> $GITHUB_ENV
         echo "my secret is $PAT_TOKEN "

     - name: run shell script
       run: |
          chmod 755 ./script.sh
          bash ./script.sh
          


  
