#java ci pipeline 
#name is an optional, it defines the name of pipeline.
name: learn-github-actions and CI PIPELINE FOR JAVA,MAVEN,DOCKERHUB.

#on is a keyword. it defines an event. 
#on:
#  push:
#    branches:  [master/.github/workflows/sample.yaml]
 # pull_request:
#    branches: [ master ]
on:
  workflow_dispatch:

    
#Define the jobs    
jobs:
  build:
    runs-on: ubuntu-latest 
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
    - name: Run the Maven verify phase
      run: mvn --batch-mode --update-snapshots verify   
    

    



  
