name: shell

on:
  push:
    branches:  [ master ]
  pull_request:
    branches: [ master ]
  #workflow_diapatch:
  



    
#Define the jobs    
jobs:
   shell_scripting:
     runs-on: ubuntu-latest 
     
     steps:
     - name: 'checkout repository on branch: ${{github.REF}}'
       uses: actions/checkout@v2
       continue-on-error: ${{ env.CONTINUE_ON_ERROR }}
       with:

           ref: ${{ github.REF }}
           fetch-depth: 0
     - name: Run shell script
       run: |
         chmod 755 ./script.sh
         ./script.sh





       
    
    

  
    
    

    



  
