#java ci pipeline 
#name is an optional, it defines the name of pipeline.
name: learn-github-actions and CI PIPELINE FOR JAVA,MAVEN,DOCKERHUB.

#on is a keyword. it defines an event. 
on:
  push:
  #checkout branch 
    branches:
    - master


#Define the jobs    
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    #uses is an action where we have to select an action
    - uses: action/checkout@v2

    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
        
      
    

    



  
